# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-12-31 21:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notice', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=128, null=True)),
                ('place', models.CharField(max_length=128, null=True)),
                ('lecturer', models.CharField(max_length=128, null=True)),
                ('title', models.CharField(max_length=128)),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notice.Notice')),
            ],
        ),
    ]
