# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-12-31 21:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalCalendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classes', models.TextField()),
                ('xt_id', models.CharField(db_index=True, max_length=32, null=True)),
            ],
        ),
    ]
