# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-12-31 21:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userpage', '0001_initial'),
        ('homework', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_nick', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=128)),
                ('type', models.IntegerField()),
                ('detail', models.TextField()),
                ('contact', models.CharField(max_length=128)),
                ('published', models.DateTimeField()),
                ('last_update', models.DateTimeField(default=None, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userpage.Student')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homework.Course')),
            ],
        ),
    ]
