# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-12-31 21:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_model_changes.changes


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userpage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xt_id', models.CharField(max_length=32)),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CourseStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ignored', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homework.Course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userpage.Student')),
            ],
            bases=(models.Model, django_model_changes.changes.ChangesMixin),
        ),
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xt_id', models.CharField(max_length=32)),
                ('title', models.TextField()),
                ('start_time', models.DateField()),
                ('end_time', models.DateField()),
                ('detail', models.TextField()),
                ('attachment', models.TextField(default=None, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homework.Course')),
            ],
        ),
        migrations.CreateModel(
            name='HomeworkStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted', models.BooleanField(default=False)),
                ('graded', models.BooleanField(default=False)),
                ('grading', models.TextField(default=None, null=True)),
                ('grading_comment', models.TextField(default=None, null=True)),
                ('graded_by', models.CharField(default=None, max_length=32, null=True)),
                ('ignored', models.BooleanField(default=False)),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homework.Homework')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userpage.Student')),
            ],
            bases=(models.Model, django_model_changes.changes.ChangesMixin),
        ),
    ]
