# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-12-02 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=128),
        ),
    ]
