# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-12-12 20:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeworkstatus',
            name='ignored',
            field=models.BooleanField(default=False),
        ),
    ]
