# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-12-10 16:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursestatus',
            name='ignored',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='coursestatus',
            name='course',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='status', to='homework.Course'),
        ),
        migrations.AlterField(
            model_name='homeworkstatus',
            name='homework',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='status', to='homework.Homework'),
        ),
    ]
