# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-12-02 12:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0002_auto_20161202_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='homework',
            name='detail',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='homework',
            name='title',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='homeworkstatus',
            name='grading',
            field=models.TextField(),
        ),
    ]
