# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-12-05 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0003_auto_20161202_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='xt_id',
            field=models.CharField(max_length=32),
        ),
    ]
