# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-12-06 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0004_auto_20161205_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeworkstatus',
            name='graded_by',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homeworkstatus',
            name='grading_comment',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
