# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-12-06 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0005_auto_20161206_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='attachment',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
