# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-12-05 12:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userpage', '0004_remove_student_xt_pw'),
        ('notice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoticeStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='notice',
            name='xt_id',
            field=models.CharField(default=None, max_length=32),
        ),
        migrations.AddField(
            model_name='noticestatus',
            name='notice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notice.Notice'),
        ),
        migrations.AddField(
            model_name='noticestatus',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userpage.Student'),
        ),
    ]
