# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-12-06 20:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_id', models.CharField(max_length=50, unique=True)),
                ('t_title', models.TextField()),
            ],
        ),
    ]
