# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-29 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('xt_id', models.CharField(db_index=True, max_length=32, null=True, unique=True)),
                ('xt_pw', models.CharField(max_length=64)),
            ],
        ),
    ]
