# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-12-13 12:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userpage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preference',
            name='s_class',
        ),
        migrations.RemoveField(
            model_name='preference',
            name='s_ddl',
        ),
    ]
