# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-29 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='xt_token',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='xt_pw',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
