# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-12-08 08:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userpage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_work', models.BooleanField(default=True)),
                ('ahead_time', models.IntegerField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userpage.Student')),
            ],
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='student',
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
