# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-12-10 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpage', '0002_auto_20161208_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='preference',
            name='s_academic',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='preference',
            name='s_class',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='preference',
            name='s_grading',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='preference',
            name='s_lecture',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='preference',
            name='s_notice',
            field=models.BooleanField(default=True),
        ),
    ]
