# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-30 12:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userpage', '0002_auto_20161129_1320'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='xt_token',
            new_name='token',
        ),
    ]
