# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-12-02 12:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userpage', '0003_auto_20161130_1245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='xt_pw',
        ),
    ]
